### ISSUE TITLE
Problem with Camel Route Builders

### ISSUE THREAD

**Issue by Panchitoboy** [astefanutti/camel-cdi#1]
Hi @astefanutti , 

Sorry for my english, i'll make my best effort for write this.

I really appreciate your work with this project. I really hope that it'll be included in Camel. It works for me better than the original version, but i have the next issues:

I want to create routes in camel from a database. At first i tryed to some thing like that

public class GeneralRouteBuilder extends RouteBuilder {

@Inject
 CamelRouteBoundary sb;

@Override 
public void configure() 
{
        sb.findAll();
}

}

CamelRouteBoundary  is a @Stateless EJB

When i do that, it hangs, i dont know what happen but it doesn't write in the logs or anything.

After that i tryed to extends RouteBuilder, this time with private field and assing the info there, but my problem is: when  i deploy the application, Camel try to register my class (because is a subclass the RouteBuilder). I want to know if there is a way to say camel to ignore my class.

This error is in WildFly 8.1.0.Final

Best regards,

**Comment by astefanutti** [comment]
Hi @Panchitoboy,

I assume that you've managed to work this out by the time. I'm closing this issue. Do not hesitate to reopen it.
