### ISSUE TITLE
Cannot resolve named bean in CdiCamelRegistry

### ISSUE THREAD

**Issue by almailer** [astefanutti/camel-cdi#15]
Hello,

I've been working with camel-cdi with some simple routes, but find I cannot get beans into the camel registry.

I have the following:

```
  public static final String LOG_BEAN_NAME = "SmsCamelRouteLog";

  public String getLogUri (LoggingLevel level) {
    return format("log:%s?logger=#%s&level=%s&showAll=true", SmsCamelRoute.class.getName(), LOG_BEAN_NAME, level.name());
  }

  @Produces
  @Named(LOG_BEAN_NAME)
  public Logger getLogForSmsCamelRoute () {
    return LoggerFactory.getLogger(SmsCamelRoute.class);
  }
```

However, I get an exception starting the route indicating the bean cannot be found in the registry. Placing a debug at line 35 of BeanManagerHelper, I find that:

manager.getBeans(name) returns an empty set, while
manager.getBeans(type) returns a set containing only the correct producer method, and
manager.getBeans(type).iterator().next().getName().equals(name) returns true (?!)

Do I have something wrong in how I register the producer method?

I'm using:

JBoss AS 6.4.9.GA
Weld 1.1
Camel 2.17.2

Many thanks!

**Comment by astefanutti** [comment]
It looks like an issue in Weld (whose version is quite old in JBoss AS 6). The producer method looks fine and having the bean manager behaving as per your experiments tends to confirm that assumption.

I would suggest you isolate the issue in a minimal test case if possible (that is removing Camel from the equation) and submit the issue to the Weld project if confirmed.

**Comment by almailer** [comment]
I will look into that.

I am unlikely to be able to update our versions of Weld or JBoss. Are you able to suggest any workarounds?

**Comment by astefanutti** [comment]
I for sure understand you may have constraints when it comes to upgrading your environment.

You could possibly customise your Camel context, at the application level, and set a custom `Registry` that would override the lookup by name operation and work-around that Weld issue based on the outcome of experiments, that is replacing the `manager.getBeans(name)` call by a lookup by type and iterating over the result to filter on the bean name. You could use `org.apache.camel.impl.CompositeRegistry` to favour composition. As for customising the Camel context, this is just a matter of declaring a `CamelContext` bean, a small price to pay compare to upgrading Weld or patching Camel CDI.

Let me know.

**Comment by almailer** [comment]
Many thanks for the help! I close this issue.
