### ISSUE TITLE
Wrong default (empty) context name lookup

### ISSUE THREAD

**Issue by christianbauer** [astefanutti/camel-cdi#5]
```
@ContextName
public class ExampleRoutes extends RouteBuilder {

    @Override
    public void configure() throws Exception {
...
```

In CdiCamelExtension:

```
        for (Bean<?> bean : manager.getBeans(RoutesBuilder.class, AnyLiteral.INSTANCE)) {
            ContextName name = CdiSpiHelper.getQualifierByType(bean, ContextName.class);
            CamelContext context = camelContexts.get(name != null ? name.value() : defaultContextName);
            if (context != null)
                addRouteToContext(bean, context, manager, adv);
            else
                adv.addDeploymentProblem(new DeploymentException("No corresponding Camel context found for RouteBuilder bean [" + bean + "]"));
        }
```

The default value of ContextName#value is an empty String, therefore the defaultContextName is not used if you only specify @ContextName for simple route discovery, expecting the default Camel context to be used.

Btw, the Camel Spring Boot extension has similar issues as the ones you are trying to fix in this project. I've opened a report here: https://issues.apache.org/jira/browse/CAMEL-8325

**Comment by astefanutti** [comment]
@christianbauer I removed the default empty value for the `@ContextName` qualifier in commit a9e9460. To use the default Camel context, you just have to use the `@Default` built-in CDI qualifier, e.g.:

    public class ExampleRoutes extends RouteBuilder {

        @Override
        public void configure() throws Exception {

        }
    }

As the `@ContextName` annotation is now declared as a CDI qualifier, I find it more consistent to use the `@Default` qualifier wherever the default Camel context is to be referenced, for example in `RouteBuilder` instances.

Let me know your opinion and close the issue if that works for you. It's not in release `1.1.0` though I can cut a release if needed. Besides, we're working on having this component merged into the Apache Camel project soon as discussed in #7.
