### ISSUE TITLE
Contributing back to Apache Camel

### ISSUE THREAD

**Issue by davsclaus** [astefanutti/camel-cdi#7]
Hi

Great work guys. The camel-cdi from Apache Camel surely has its issues and over time we have identified more and more issues/errors. Great that all of those are being addressed or has been addressed in this github project.

As we are closing down on the new Camel 2.15 release I wonder how far this work is from being able to donated and replace the old crusty camel-cdi component?

My though we be that we drop the camel-cdi we have at Apache and drop in your work as-is.

PS: Sorry of using a issue to ask about this. But github makes this much easier to just use a ticket.

**Comment by astefanutti** [comment]
Hi Claus,

The major point to be addressed is the compatibility with older versions of the CDI specification. Indeed, that version of the `camel-cdi` component requires CDI 1.2 while the existing version within the Camel codeline is compatible with CDI 1.0. Adaptation to alleviate that constraint is possible though that might be a bit short if you're targeting Q1 2015 for the 2.15.0 release. Decision to provide that support belong to @antoinesd.

That version of the component requires Java 7 which is OK since Camel requires it since version 2.14.0 onwards AFAIK.

Besides that, I'm planning to polish a bit the API for the CDI event endpoint introduced in #6 though that can be done within a couple of days. Last but not least, the [component documentation](http://camel.apache.org/cdi.html) needs a complete overhaul.

I let @antoinesd and @cmoulliard comment on this.

No worries for the issue tracking :-)

**Comment by davsclaus** [comment]
Yeah sound good. 

So lets schedule this for Camel 2.16 which gives more time to finish this work.

**Comment by antoinesd** [comment]
HI Guys,

As @astefanutti said I'm planning to work on CDI 1.0 back port. I plan to create a branch CDI-1.0 from master to do so. My main question is about differentiating both camel-cdi version. Should we change artifact name to be clear or be based only on artifact version with the risk of having user mixing version for CDI 1.2 and CDI 1.0?
I'm also ok to give some help for the documentation.

**Comment by davsclaus** [comment]
The current camel-cdi has bugs and not really so active maintained.

I would rather let you the CDI experts work on a replacement, and dont bother about the current came-cdi from Apache Camel. Also dont bother about supporting older CDI 1.0. 

Then when you guys think your work is ready, we replace yours into Apache Camel. Then we have a great camel-cdi component that you guys are more than welcome to help keep up to date and awesome.

If we can get this into the next Camel 2.16 release that would be fantastic.

**Comment by antoinesd** [comment]
The motivation ro have a CDI 1.0 support is related to the fact that today, the last JBoss EAP version doesn't support CDI 1.1+. If we want to provide a Camel-CDI solution for supported EAP customer we need this.
I'm currently working on this back porting. I think it should be available before the end the week. I keep you posted in the coming days if my prevision was too optimistic ;).

**Comment by antoinesd** [comment]
Ok, I just push a PR (see #9) for CDI 1.0 code backport. All tests are ok. The known limitations are:
* Doesn't support jdk8. Probably due to Weld 1.1.x
* Endpoint events bridge doesnt support parameterized type as payload: a CDI 1.0 limitation

**Comment by astefanutti** [comment]
I've just merged PR #9 into the [`cdi-1.0`](../tree/cdi-1.0) branch. We still have to decide what's the best way to manage support for multiple CDI specification versions into the same Camel codeline.

My current opinion is to have mutliple Camel CDI modules to concile the needs for both customer based support and upstream innovation at the same time, e.g.: `org.apache.camel:camel-cdi-1.0`, `org.apache.camel:camel-cdi-1.2`, `org.apache.camel:camel-cdi-2.0`.

Besides that point, I plan to add a last feature that will enable to do Camel DSL AOP instrumentation with CDI observer methods. Then, I'll work on the [component documentation](http://camel.apache.org/cdi.html) starting with the [README](../blob/master/README.md) file I've maintained so far.

**Comment by davsclaus** [comment]
How are you guys doing? After summer we will close down on the next Apache Camel release and would like to include all this improved camel-cdi stuff out of the box.

**Comment by astefanutti** [comment]
Hi Claus, hope you're doing well. I'll be working on the integration into Camel codeline ASAP. Would you have an idea on the expected release date roughly, like beginning of September, so that I can schedule my work and not miss `2.16.0`?

**Comment by davsclaus** [comment]
Yeah I would say mid August if we get around it sooner. But there abouts.

**Comment by cmoulliard** [comment]
I will help you Antonin for that integration. Ping me beginning of August.

Charles

On Fri, Jun 5, 2015 at 5:48 PM, Claus Ibsen <notifications@github.com>
wrote:

> Yeah I would say mid August if we get around it sooner. But there abouts.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astefanutti/camel-cdi/issues/7#issuecomment-109337403>
> .
>



-- 
Charles Moulliard
Apache Committer / Architect @RedHat
Twitter : @cmoulliard | Blog :  http://cmoulliard.github.io

**Comment by astefanutti** [comment]
Ok, sounds good to me!

**Comment by astefanutti** [comment]
Hi guys, I'm done with a first round of integration into the Camel codeline. I've updated and tested successfully the following pieces:
- [x] Camel CDI component with CDI 1.0 and CDI 1.2 compatibility,
- [x] CDI Maven dependencies management,
- [x] Camel CDI integration tests,
- [x] CDI bootstrap and Camel Maven plugin CDI support,
- [x] Camel CDI example Maven archetype,
- [x] Camel assembly.

The current work can be found here: https://github.com/astefanutti/camel/commits/camel-cdi.

While everything works fine, that first round have the CDI compatibility coded into the Maven artifact id, i.e., producing two artifacts `org.apache.camel:camel-cdi-1.0` and `org.apache.camel:camel-cdi-1.2`, which I find not entirely satisfying both from the end-user and the source code standpoints (code duplication).

While the later can be alleviated with an extra module that could be shaded into the two main artifacts, the former should ideally be solved by having a single CDI component that would automatically pick up the appropriate CDI extension and set of beans at runtime. Unfortunately, while dynamically vetoing beans is possible, I don't know of any ways to _profile / activate / deactivate_ a CDI extension dynamically at runtime (maybe @antoinesd can bring some expertise here).

The only other option that I see to avoid coding the CDI version into the artifact id would be to use the Maven classifier as it is done for JDK version like `jdk15`, e.g.:

    <dependency>
        <groupId>org.apache.camel</groupId>
        <artifactId>camel-cdi</artifactId>
        <classifier>cdi12</classifier>
        <version>2.16.0</version>
    </dependency>

Besides that, the remaining actions that I can think of are:
- [ ] OSGi support,
- [ ] Documentation.

**Comment by rajbarua** [comment]
Hello Antonin,

Thanks for working on this enhanced Camel CDI integration. I wanted to use some of the enhancements but I wasn't sure if this made it to 2.16.0. As far as I could tell, Camel still uses the old CDI integration. Is this project now planned to be merged in next release or so?

Thanks,
Raj

**Comment by astefanutti** [comment]
@rajbarua Your understanding is correct. We are actively working on having it merged for version 2.17.0. I'll keep you posted on the progress.

**Comment by astefanutti** [comment]
I've just created apache/camel#769.

**Comment by astefanutti** [comment]
Merged in apache/camel@0421c24dfcf992f3296ed746469771e3800200e3.
