### ISSUE TITLE
Question: Is it possible to use JSF Managed Beans as 'from' of a route?

### ISSUE THREAD

**Issue by scsynergy** [astefanutti/camel-cdi#8]
Sorry for abusing an issue for contacting you, but I am looking for advice from someone who knows CDI and Camel and you seem to be the one with the most expertise.

My question is: Can I use a JSF Managed Bean as the 'from' or 'to' part of a route - and how? I am writing an application that uses Wildfly 8.2.0 with WELD, JSF and Camel 2.14.1. The idea is to let users configure any arbitrary workflow (including human interaction through web pages) to route documents like e. g. invoices from endpoint to endpoint.

An example:
A user logs into our web application and uploads an invoice via the upload button. As the document was defined as an invoice during upload, a previously defined camel route is triggered which sends the invoice to the accounting department's TODO list. An accountant sees the new document in his TODO list, checks whether it is valid and ticks the 'approved' checkbox. The document is then sent on to the external accounting software via another camel component.

Is it even possible to define this entire workflow as a single camel route? Or do we have to devide it into many smaller pieces which consist of routes and non-camel routes? 
1. non-camel route: JSF.producerUpload -> JMS
2. camel route: 'route.from' is triggered by a message arriving via JMS, passes it on to a filter / recipient list which saves the document to the data base
3. non-camel route: JSF TODO list is populated with the document from the data base, user presses save which sends the document to JMS
4. camel route: 'anotherRoute.from' picks the message up off the JMS queue and passes it on to the component which delivers it to the accounting software

What we would prefer to achieve is:
'route.from(jsf:upload).beanRef(filter).beanRef(addToTodoList).beanRef(jsf:approve).to(ftp:accounting)

Mind you, the route here is just an example, users should be allowed to change their workflow / routes without the need for a developer to intervene.

Thank you for reading and best regards
Ronny

**Comment by astefanutti** [comment]
Hi @scsynergy,

Sorry for the late reply. You may have sorted this out already though here are my elements.

The `from` and `to` instructions operate on _endpoints_ which means you have to have corresponding Camel components behind the scene. Thus, this is not possible to use a JSF managed bean directly with these instructions. You can rather use the Camel [bean integration](http://camel.apache.org/bean-integration.html) features to call your managed bean into Camel routes. For instance, when a user uploads an invoice, you can use the `@Produce` annotation to get a producer to send the corresponding message to your integration workflow.

Hope that helps.

**Comment by scsynergy** [comment]
Thank you for your response!
I tried what you suggested, but hit a wall because we use a dynamic multi-tenant appraoch: 
When a user uploads an invoice I need to hit a specific CDICamelContext via the @Produces method - the one matching the user's tenant ID. But since annotations need a constant value expression I cannot simply say @Produces getEndpoint(@ContextName("generated programatically")) {return tenant specific Endpoint}. 
How would I go about writing a producer method that takes a ContextName as a parameter whose value is generated programmatically and how may I generate a ContextName with a value dynamically, e. g. @Inject @ContextName("tenant Id 5")?

On a side note: Are you available for short-term hire as a freelancer? And would you be interested in writing a JSF-CDI-Camel component to provide the feature we need?

**Comment by astefanutti** [comment]
You can use the CDI [programmatic lookup](http://docs.jboss.org/cdi/spec/1.2/cdi-spec.html#programmatic_lookup) mechanism to retrieve bean contextual references based on dynamic annotation literals, e.g.:
```
@Inject
Instance<Endpoint> endpoint;

Endpoint tenantEndpoint = endpoint.select(new ContextName.Literal("tenant")).get();
```
Regarding your feature request, I'm not available. One option would be to contact the Red Hat JBoss Fuse team should that be a strong requirement for you.

**Comment by astefanutti** [comment]
@scsynergy, let me know if you need further assistance. I'm closing this issue though feel free to re-open it should that be the case.
